// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solar_Facts.DAL;

namespace Solar_Facts.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210119101025_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Solar_Facts.DAL.Models.PlanetAndDwarfPlanet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DiameterInKM")
                        .HasColumnType("int");

                    b.Property<int>("KnownMoons")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrbitDistanceInKM")
                        .HasColumnType("bigint");

                    b.Property<double>("OrbitPeriodInDays")
                        .HasColumnType("float");

                    b.Property<int>("StarId")
                        .HasColumnType("int");

                    b.Property<int>("SurfaceTempMax")
                        .HasColumnType("int");

                    b.Property<int>("SurfaceTempMin")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StarId");

                    b.ToTable("PlntAndDPlnt");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiameterInKM = 4879,
                            KnownMoons = 0,
                            Name = "Mercury",
                            OrbitDistanceInKM = 57900000L,
                            OrbitPeriodInDays = 88.0,
                            StarId = 1,
                            SurfaceTempMax = -173,
                            SurfaceTempMin = -427,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            DiameterInKM = 12104,
                            KnownMoons = 0,
                            Name = "Venus",
                            OrbitDistanceInKM = 108200000L,
                            OrbitPeriodInDays = 224.69999999999999,
                            StarId = 1,
                            SurfaceTempMax = 462,
                            SurfaceTempMin = 462,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            DiameterInKM = 12756,
                            KnownMoons = 1,
                            Name = "Earth",
                            OrbitDistanceInKM = 149600000L,
                            OrbitPeriodInDays = 224.69999999999999,
                            StarId = 1,
                            SurfaceTempMax = 58,
                            SurfaceTempMin = -88,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            DiameterInKM = 6805,
                            KnownMoons = 2,
                            Name = "Mars",
                            OrbitDistanceInKM = 227900000L,
                            OrbitPeriodInDays = 693.96000000000004,
                            StarId = 1,
                            SurfaceTempMax = -63,
                            SurfaceTempMin = -63,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            DiameterInKM = 950,
                            KnownMoons = 0,
                            Name = "Ceres",
                            OrbitDistanceInKM = 413700000L,
                            OrbitPeriodInDays = 1680.1099999999999,
                            StarId = 1,
                            SurfaceTempMax = -105,
                            SurfaceTempMin = -105,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            DiameterInKM = 142984,
                            KnownMoons = 67,
                            Name = "Jupiter",
                            OrbitDistanceInKM = 778300000L,
                            OrbitPeriodInDays = 4346.3800000000001,
                            StarId = 1,
                            SurfaceTempMax = -108,
                            SurfaceTempMin = -108,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            DiameterInKM = 120536,
                            KnownMoons = 62,
                            Name = "Saturn",
                            OrbitDistanceInKM = 1400000000L,
                            OrbitPeriodInDays = 10774.65,
                            StarId = 1,
                            SurfaceTempMax = -139,
                            SurfaceTempMin = -139,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            DiameterInKM = 51118,
                            KnownMoons = 27,
                            Name = "Uranus",
                            OrbitDistanceInKM = 2900000000L,
                            OrbitPeriodInDays = 30680.369999999999,
                            StarId = 1,
                            SurfaceTempMax = -197,
                            SurfaceTempMin = -197,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            DiameterInKM = 49528,
                            KnownMoons = 14,
                            Name = "Neptune",
                            OrbitDistanceInKM = 4500000000L,
                            OrbitPeriodInDays = 60191.959999999999,
                            StarId = 1,
                            SurfaceTempMax = -201,
                            SurfaceTempMin = -201,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            DiameterInKM = 2306,
                            KnownMoons = 5,
                            Name = "Pluto",
                            OrbitDistanceInKM = 5900000000L,
                            OrbitPeriodInDays = 89849.649999999994,
                            StarId = 1,
                            SurfaceTempMax = -229,
                            SurfaceTempMin = -229,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            DiameterInKM = 1739,
                            KnownMoons = 2,
                            Name = "Haumea",
                            OrbitDistanceInKM = 6400000000L,
                            OrbitPeriodInDays = 103473.2,
                            StarId = 1,
                            SurfaceTempMax = -241,
                            SurfaceTempMin = -241,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            DiameterInKM = 1434,
                            KnownMoons = 0,
                            Name = "Makemake",
                            OrbitDistanceInKM = 6900000000L,
                            OrbitPeriodInDays = 113188.64999999999,
                            StarId = 1,
                            SurfaceTempMax = -241,
                            SurfaceTempMin = -241,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            DiameterInKM = 1434,
                            KnownMoons = 1,
                            Name = "Eris",
                            OrbitDistanceInKM = 10100000000L,
                            OrbitPeriodInDays = 204864.51999999999,
                            StarId = 1,
                            SurfaceTempMax = -241,
                            SurfaceTempMin = -241,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Solar_Facts.DAL.Models.SolarSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SolarSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "The Solar system"
                        });
                });

            modelBuilder.Entity("Solar_Facts.DAL.Models.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("Age")
                        .HasColumnType("bigint");

                    b.Property<int>("CoreTemp")
                        .HasColumnType("int");

                    b.Property<int>("DiameterInKM")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolarSystemId")
                        .HasColumnType("int");

                    b.Property<int>("SurfaceTempMax")
                        .HasColumnType("int");

                    b.Property<int>("SurfaceTempMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolarSystemId");

                    b.ToTable("Stars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 4600000000L,
                            CoreTemp = 15000000,
                            DiameterInKM = 1392694,
                            Name = "The Sun",
                            SolarSystemId = 1,
                            SurfaceTempMax = 5500,
                            SurfaceTempMin = 5500
                        });
                });

            modelBuilder.Entity("Solar_Facts.DAL.Models.PlanetAndDwarfPlanet", b =>
                {
                    b.HasOne("Solar_Facts.DAL.Models.Star", "StarToOrbit")
                        .WithMany("Planets")
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StarToOrbit");
                });

            modelBuilder.Entity("Solar_Facts.DAL.Models.Star", b =>
                {
                    b.HasOne("Solar_Facts.DAL.Models.SolarSystem", "solarSystem")
                        .WithMany("Stars")
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("solarSystem");
                });

            modelBuilder.Entity("Solar_Facts.DAL.Models.SolarSystem", b =>
                {
                    b.Navigation("Stars");
                });

            modelBuilder.Entity("Solar_Facts.DAL.Models.Star", b =>
                {
                    b.Navigation("Planets");
                });
#pragma warning restore 612, 618
        }
    }
}
